/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-19 03:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.cinema.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.cinema");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	/* List<Local> localList = (List<Local>)request.getAttribute("localList");
    	List<Theater> theaterList = (List<Theater>)request.getAttribute("theaterList"); */
    	int cPage;
		try {
			cPage = Integer.parseInt(request.getParameter("cPage"));
		} catch (NumberFormatException e) {
			//cPage 파라미터가 값이 없거나, 부정 입력된 경우 대비 
			cPage=1;
		}
    
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tth, td, tr{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.tab{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\ttop : 0;\r\n");
      out.write("\t\tleft : 0;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.div-enroll{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\ttop : 5%;\r\n");
      out.write("\t\tleft : 10%;\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable#notice-table{\r\n");
      out.write("\t\tdisplay : block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.update-event{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\timg{\r\n");
      out.write("\t\twidth: 250px;\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.div-inline{\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2>고객센터</h2>\r\n");
      out.write("\t<div class='tab' id='noticeList'>공지사항</div>\r\n");
      out.write("\t<div class='tab' id='eventList'>이벤트</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 공지사항 등록 폼 -->\r\n");
      out.write("\t<div id=\"div-notice-enroll\" class='div-enroll'>\r\n");
      out.write("\t\t<span class=\"close\">&times;</span>\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardEnroll\" method='post' enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"type\" value='notice' />\r\n");
      out.write("\t\t\t공지사항\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t제목 : <input type=\"text\" name=\"title\" id=\"title\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t영화관 지역 정보 : \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"local\" id=\"local\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t영화관 지점 정보 : \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"theater\" id=\"theater\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t이미지 : <input type=\"file\" name=\"up_notice_file\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t내용 : <textarea name=\"content\" id=\"\" cols=\"20\" rows=\"10\"></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"등록\" />\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"취소\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 공지사항 -->\r\n");
      out.write("\t<div id=\"boardView\"></div>\r\n");
      out.write("\t<div id=\"none\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//페이지 로드시, noticeList 버튼 클릭\r\n");
      out.write("\t\twindow.onload = pageLoad;\r\n");
      out.write("\t    function pageLoad(){\r\n");
      out.write("\t    \tdocument.getElementById(\"noticeList\").click();\r\n");
      out.write("\t    };\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t//공지사항 탭\r\n");
      out.write("\t\t\t$(\"#noticeList\").click(function(){\r\n");
      out.write("\t\t\t\tvar noticeType = this.id;\r\n");
      out.write("\t\t\t\t//$(\"div#none\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\t\tdata : {listType : noticeType, cPage : ");
      out.print(cPage);
      out.write("},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar nhtml = \"<input type='button' value='등록' id='btn-notice-enroll'/>\";\r\n");
      out.write("\t\t\t\t\t\tvar html = \"<table id='notice-table'>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<tr><th>no</th><th>지역/영화관</th><th>제목</th><th>등록일</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\t\treturn b.bdid-a.bdid;\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tvar pageBar;\r\n");
      out.write("\t\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\t\tvar d = new Date(i.regdate.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<tr>\"+ \"<td>\" + i.bdid + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td>\" + i.tinfo + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td><a href='");
      out.print(request.getContextPath());
      out.write("/board/boardDetail?bdid=\"+i.bdid+\"'>\" + i.title + \"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td>\" + d.getFullYear() + \"-\" + (d.getMonth()+1) + \"-\" + d.getDate() + \"</td>\" +\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tpageBar = i.pageBar;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\thtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tconsole.log(pageBar);\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div id='pageBar'>\"+pageBar+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#boardView\").html(nhtml);\r\n");
      out.write("\t\t\t\t\t\t$(\"div#none\").html(html);\r\n");
      out.write("\t\t\t\t\t\t$(\"#btn-notice-enroll\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#div-notice-enroll\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t\t});//btn-notice-enroll 버튼\r\n");
      out.write("\t\t\t\t\t\t$(\".close\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".div-enroll\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"div#none\").on(\"click\",\"#\"+");
      out.print(cPage);
      out.write(", function(){\r\n");
      out.write("\t\t\t\t\t\t\tpageBar = \"<span value='\"+");
      out.print(cPage-1);
      out.write("+\"'>\"+");
      out.print(cPage-1);
      out.write("+\"</span><a href=/project/board/boardView?cPage=\"+");
      out.print(cPage);
      out.write("+\" id='\"+");
      out.print(cPage);
      out.write("+\"'><span value='\"+");
      out.print(cPage);
      out.write("+\"'>\"+");
      out.print(cPage);
      out.write("+\"</span></a>\";\r\n");
      out.write("\t\t\t\t\t\t\tvar h = \"<div id='pageBar'>\"+pageBar+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t$(\"div#none\").append(h);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});//ajax\r\n");
      out.write("\t\t\t});//notice 버튼\r\n");
      out.write("\t\t});//function\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 이벤트 등록 폼 -->\r\n");
      out.write("\t<div id=\"div-event-enroll\" class='div-enroll'>\r\n");
      out.write("\t\t<span class=\"close\">&times;</span>\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/boardEnroll\"  method='post' enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"type\" value='event' />\r\n");
      out.write("\t\t\t이벤트\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t제목 : <input type=\"text\" name=\"title\" id=\"\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t영화관 지역 정보 : \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"local\" id=\"local\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t영화관 지점 정보 : \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"theater\" id=\"theater\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t이미지 : <input type=\"file\" name=\"up_event_file\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t내용 : <textarea name=\"content\" id=\"img\" cols=\"20\" rows=\"10\"></textarea>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t시작:\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"startterm\" id=\"startterm\" /> 시작이 끝보다 작아야한다.\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t끝:\r\n");
      out.write("\t\t\t<input type=\"date\" name=\"endterm\" id=\"endterm\" />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"등록\" id='eventTime'/>\r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"취소\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 이벤트 팝업창 -->\r\n");
      out.write("\t<div id=\"event-popup\" class='div-enroll'>\r\n");
      out.write("\t\t<span class=\"close\">&times;</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar pPage=8;\r\n");
      out.write("\t\tvar lPage=8;\r\n");
      out.write("\t\t$(\"#eventList\").click(function(){\r\n");
      out.write("\t\t\tvar html = \"<input type='button' value='등록' id='btn-event-enroll'/>\";\r\n");
      out.write("\t\t\thtml += \"<input type='radio' name='event-status' id='present' class='present' checked><label for='present'>진행 중인 이벤트</label>\";\r\n");
      out.write("\t\t\thtml += \"<input type='radio' name='event-status' id='last' class='last'><label for='last'>지난 이벤트</label>\";\t\t\t\r\n");
      out.write("\t\t\t$(\"#boardView\").html(html);\r\n");
      out.write("\t\t\tfn_add_present();\r\n");
      out.write("\t\t\t$(\"#boardView\").on(\"change\",\"[name=event-status]\",function(){\r\n");
      out.write("\t\t\t\tif(this.id==\"present\"){\r\n");
      out.write("\t\t\t\t\tfn_add_present();\t\r\n");
      out.write("\t\t\t\t\tlPage=8;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(this.id==\"last\"){\r\n");
      out.write("\t\t\t\t\tfn_add_last();\t\r\n");
      out.write("\t\t\t\t\tpPage=8;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//등록 버튼을 누르면 팝업창이 나옴.\r\n");
      out.write("\t\t\t$(\"#boardView\").on(\"click\",\"#btn-event-enroll\", function(){\r\n");
      out.write("\t\t\t\t$(\"#div-event-enroll\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//등록 팝업창의 닫기 버튼\r\n");
      out.write("\t\t\t$(\".div-enroll\").on(\"click\",\".close\", function(){\r\n");
      out.write("\t\t\t\t$(\".div-enroll\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t$(\".div-enroll input\").val(\"\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//이벤트 등록 시작시간과 끝시간의 잘못된 설정을 막아준다.\r\n");
      out.write("\t\t\t$(\"#eventTime\").click(function(){\r\n");
      out.write("\t\t\t\tvar startterm = $(\"#startterm\").val().split(\"-\");\r\n");
      out.write("\t\t\t\tvar endterm = $(\"#endterm\").val().split(\"-\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//2018-5-12 ~ 2018-4-18과 같이 시간을 잘못 설정할 경우\r\n");
      out.write("\t\t\t\tif(startterm[0]*1+startterm[1]/12>endterm[0]*1+endterm[1]/12){\t//2018*(월/12)의 값이 시작시간이 클 경우\r\n");
      out.write("\t\t\t\t\talert(\"이벤트 기간 설정을 잘못 했습니다.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if((startterm[0]*1+startterm[1]/12==endterm[0]*1+endterm[1]/12) && startterm[2]>endterm[2]){//2018*(월/12)의 값이 시작과 끝 시간이 같으면서 시작 일수가 클 경우\r\n");
      out.write("\t\t\t\t\talert(\"이벤트 기간 설정을 잘못 했습니다.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"이벤트가 등록되었습니다.\");\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_add_present(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\tdata : {listType : \"eventList\", status: \"present\", pPage: pPage},\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar phtml=\"\";\r\n");
      out.write("\t\t\t\t\tvar presentEventCnt=0;\r\n");
      out.write("\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\treturn a.order-b.order;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\tvar d = new Date();\r\n");
      out.write("\t\t\t\t\t\tvar ds = new Date(i.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\tvar de = new Date(i.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t//끝나는 시간이 현재 시간보다 크거나 같으면 현재 진행중인 이벤트\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<div class='div-inline' id='eventp\"+presentEventCnt+\"'>\"\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<table class='table' id=\"+i.bdid+\">\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td>\"+ \"<img id='clickEvent' src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ i.img +\"' / >\" + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td> \"+ i.title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td>\" + ds.getFullYear() + \"-\" + (ds.getMonth()+1) + \"-\" + ds.getDate() + \" ~ \"  + de.getFullYear() + \"-\" + (de.getMonth()+1) + \"-\" + de.getDate()+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"</div>\"\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt%4==3){\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt==(pPage-1)){\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"<input type='button' id='add-present' value='더보기'>\";\t\t\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tpresentEventCnt++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").html(phtml);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//지난 이벤트의 더보기 버튼\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"#add-present\",function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt==pPage){\r\n");
      out.write("\t\t\t\t\t\t\tpPage += 8;\r\n");
      out.write("\t\t\t\t\t\t\tfn_add_present();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//on 동적으로 부모의 자식이벤트를 달아준다. //단, 부모는 동적으로 생성되면 안된다.\r\n");
      out.write("\t\t\t\t\t//현재 진행중인 이벤트, 지난 이벤트의  수정 팝업창\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"table.table\", function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(this.id);\r\n");
      out.write("\t\t\t\t\t\tvar html=\"\";\r\n");
      out.write("\t\t\t\t\t\tfor(var a in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar b = data[a];\r\n");
      out.write("\t\t\t\t\t\t\tif(b.bdid==this.id){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(b.bdid);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ds = new Date(b.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar de = new Date(b.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsYear = ds.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsMonth = ds.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsDate = ds.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deYear = de.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deMonth = de.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deDate = de.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsMonth = \"0\"+dsMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsDate = \"0\"+dsDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeMonth = \"0\"+deMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeDate = \"0\"+deDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<form action='");
      out.print(request.getContextPath());
      out.write("/board/boardEnroll' method='post' enctype='multipart/form-data' >\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='type' value='updateEvent'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='bdid' value='\"+b.bdid+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='old_file' value='\"+b.img+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<span class='close'>&times;</span><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<h3 class='event-popup'>\"+b.title+\"</h3>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='update-event'>제목 : </p><input type='text' class='update-event' name='title' value='\"+b.title+\"'/>\" ;\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='event-popup'>\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \" ~ \"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"</p><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='update-event'>제목 : </p><input type=date class='update-event' name='startterm' value='\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \"'><p class='update-event'>~</p><input type=date class='update-event' name='endterm' value='\"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"' ><br class='update-event'/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='button' value='수정' class='event-popup' ><hr class='event-popup'><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='submit' value='수정' class='update-event'><hr class='update-event'><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ b.img +\"'/ class='event-popup'>\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='file' name='up-notice-file' class='update-event' />\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"</form>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").html(html);\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").on(\"click\",\"input[type=button]\",function(){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"확인\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\".event-popup\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\".update-event\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction fn_add_last(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\tdata : {listType : \"eventList\", status: \"last\", lPage: lPage},\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar endEventCnt=0;\r\n");
      out.write("\t\t\t\t\tvar lhtml=\"\";\r\n");
      out.write("\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\treturn a.order-b.order;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\tvar ds = new Date(i.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\tvar de = new Date(i.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<div class='div-inline' id='eventl\"+endEventCnt+\"'>\"\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<table class='table' id=\"+i.bdid+\">\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\"+ \"<img id='clickEvent' src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ i.img +\"'/ >\" + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\" + i.title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\" + ds.getFullYear() + \"-\" + (ds.getMonth()+1) + \"-\" + ds.getDate() + \" ~ \"  + de.getFullYear() + \"-\" + (de.getMonth()+1) + \"-\" + de.getDate() +\"</td>\"+\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"</div>\"\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt%4==3){\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt==(lPage-1)){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(endEventCnt+\"???\");\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"<input type='button' id='add-last' value='더보기'>\";\t\t\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tendEventCnt++;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").html(lhtml);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//지난 이벤트의 더보기 버튼\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"#add-last\",function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt==lPage){\r\n");
      out.write("\t\t\t\t\t\t\tlPage += 8;\r\n");
      out.write("\t\t\t\t\t\t\tfn_add_last();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//on 동적으로 부모의 자식이벤트를 달아준다. //단, 부모는 동적으로 생성되면 안된다.\r\n");
      out.write("\t\t\t\t\t//현재 진행중인 이벤트, 지난 이벤트의  수정 팝업창\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"table.table\", function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(this.id);\r\n");
      out.write("\t\t\t\t\t\tvar html=\"\";\r\n");
      out.write("\t\t\t\t\t\tfor(var a in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar b = data[a];\r\n");
      out.write("\t\t\t\t\t\t\tif(b.bdid==this.id){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(b.bdid);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ds = new Date(b.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar de = new Date(b.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsYear = ds.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsMonth = ds.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsDate = ds.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deYear = de.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deMonth = de.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deDate = de.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsMonth = \"0\"+dsMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsDate = \"0\"+dsDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeMonth = \"0\"+deMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeDate = \"0\"+deDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<form action='");
      out.print(request.getContextPath());
      out.write("/board/boardEnroll' method='post' enctype='multipart/form-data' >\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='type' value='updateEvent'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='bdid' value='\"+b.bdid+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='old_file' value='\"+b.img+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<span class='close'>&times;</span><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<h3 class='event-popup'>\"+b.title+\"</h3>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='update-event'>제목 : </p><input type='text' class='update-event' name='title' value='\"+b.title+\"'/>\" ;\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='event-popup'>\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \" ~ \"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"</p><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='update-event'>제목 : </p><input type=date class='update-event' name='startterm' value='\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \"'><p class='update-event'>~</p><input type=date class='update-event' name='endterm' value='\"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"' ><br class='update-event'/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='button' value='수정' class='event-popup' ><hr class='event-popup'><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='submit' value='수정' class='update-event'><hr class='update-event'><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ b.img +\"'/ class='event-popup'>\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='file' name='up-notice-file' class='update-event' />\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"</form>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").html(html);\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").on(\"click\",\"input[type=button]\",function(){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"확인\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\".event-popup\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\".update-event\").css(\"display\",\"inline-block\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
