/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-21 00:35:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cinema.admin.model.vo.*;

public final class seat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/manager_header.jsp", Long.valueOf(1526815146982L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.cinema.admin.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Manager managerSession = (Manager)session.getAttribute("managerSession");
	System.out.println("유저 로긴 세션 확인 "+managerSession);
	String path = request.getContextPath();

	
	String MovieListPath = path+"/movie/showMovieList.do";
	String LocaManaging = path+"/manager/local?type=list";
	
	
	String movie = path+"/manager/movie";
	String manager = path+"/manager/manager";
	String local = path+"/manager/local";
	String theater = path+"/manager/theater";
	String seat = path+"/manager/seat";
	String room = path+"/manager/room";
	String schedule = path+"/manager/schedule";
	String ticket = path+"/manager/ticket";
	String price = path+"/manager/price";
	String board = path+"/board/boardView";

	
	
	
	Cookie[] cookies = request.getCookies();
	
	boolean saveId = false;
	String userIdSaved = "";
	
   	if(cookies !=null){
   		System.out.println("--------------------------------");
   		System.out.println("브라우져가 전송한 쿠키목록");
   		System.out.println("--------------------------------");
		for(Cookie c : cookies ){
			String key = c.getName();
			String value = c.getValue();
	   		System.out.println("쿠키가요 ===> " + key + " : " + value );
	   		
	   		//아이디저장 쿠키검사
	   		if("saveId".equals(key)){
	   			saveId = true;
	   			userIdSaved = value;
	   		}else{
	   			
	   		}
		}   		
   		System.out.println("--------------------------------");
   	}
   	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/cinema/css/jquery.datetimepicker.min.css\">\r\n");
      out.write("<script src=\"/cinema/js/jquery.datetimepicker.full.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/css/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("function fn_login_pop(){\r\n");
      out.write("\t$(\".login_pop\").toggle();\r\n");
      out.write("\tconsole.log($(\".login_pop\"));\r\n");
      out.write("}\r\n");
      out.write("function fn_login(){\r\n");
      out.write("\t$id = $(\"#id\").val();\r\n");
      out.write("\t$pw = $(\"#pw\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log($id);\r\n");
      out.write("\tconsole.log($pw);\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(path );
      out.write("/login/userlogin\", \r\n");
      out.write("\t\tdata : {id : $id, pw : $pw},\r\n");
      out.write("\t\ttype : \"post\", \r\n");
      out.write("\t\tdataType : \"html\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror :function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(){\r\n");
      out.write("\t\t\tconsole.log(\"ajax 어찌됬던 종료!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_logout(){\r\n");
      out.write("\tlocation.href=\"");
      out.print(path );
      out.write("/manager/logout\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("header{ border-bottom:3px solid #1986ff; position:relative; }\r\n");
      out.write("header h2{float:left;}\r\n");
      out.write("header h2 a{padding:10px; display:inline-block;}\r\n");
      out.write("nav{overflow:hidden;}\r\n");
      out.write("nav::after{content:\"\"; clear:both;}\r\n");
      out.write("nav > ul {float:left; margin-left:20px; overflow:hidden;}\r\n");
      out.write("nav > ul > li{float:left; border-left:1px solid #ececec; border-right:1px solid #ececec; min-width:80px; text-align:center;}\r\n");
      out.write("nav > ul > li a{padding:20px 10px; display:inline-block; width:100%;}\r\n");
      out.write("nav > ul > li a:hover{background:#333; color:#fff;}\r\n");
      out.write(".login_pop{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\twidth:500px;\r\n");
      out.write("\theight:500px;\r\n");
      out.write("\tborder:1px solid #ececec; position:absolute;\r\n");
      out.write("\tbackground:#ececec;\r\n");
      out.write("\tright:0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<h2><a href=\"");
      out.print( path);
      out.write("\">MVCINEMA</a></h2>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(movie );
      out.write("\">영화</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(manager );
      out.write("\">매니저</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(local );
      out.write("\">지역</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(theater );
      out.write("\">영화관</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(seat );
      out.write("\">M좌석 </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(room );
      out.write("\">M상영관 </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(schedule );
      out.write("\">M스케쥴</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(ticket );
      out.write("\">M예매</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(price );
      out.write("\">가격</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(board );
      out.write("\">게시판</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("function showTheaterName(tid){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(theater );
      out.write("\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdata : { type : \"selectTheater\", theaterNo : tid},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tif(data.name == undefined){\t \r\n");
      out.write("\t \t\t\t$(\".theater_where\").html(\"\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t \t\t\t$(\".theater_where\").html(data.name);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
 if(managerSession != null) { 
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tshowTheaterName(");
      out.print( managerSession.getTid() );
      out.write(");\r\n");
      out.write("})\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("\t<section id=\"content\">\r\n");
      out.write("\t\t<div class=\"manager_inforBox\">\r\n");
      out.write("\t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t");
 if(managerSession != null) {
      out.write("\r\n");
      out.write("\t\t\t<span class=\"theater_where\"></span>  ");
      out.print( managerSession.getName() );
      out.write(" 님, 안녕하세요.\r\n");
      out.write("\t\t\t<span onclick=\"fn_logout()\">로그아웃</span>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    
    String localPath = request.getContextPath()+"/manager/local";
    
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("table{}\r\n");
      out.write("table th{background:#333; color:#fff; padding:20px; font-weight:normal;}\r\n");
      out.write("table td input{width:100%; font-size:18px;}\r\n");
      out.write("table td button{width:100%;}\r\n");
      out.write("\r\n");
      out.write("#viewSeat{position:relative; overflow:hidden;}\r\n");
      out.write("#viewSeat table{border-collapse: separate; border-spacing:1px; float:left;}\r\n");
      out.write("#viewSeat .seat{width:60%}\r\n");
      out.write("#viewSeat table td{padding:2px 1px; overflow:hidden; position:relative;background:#333; color:#fff; text-align:center; min-width:15px; max-width:15px; height:15px;  cursor:pointer; font-size:11px;}\r\n");
      out.write("#viewSeat table td:hover{background:#fff; color:#333}\r\n");
      out.write("#viewSeat table .select{background:#333; color:#333; background:#ececec;}\r\n");
      out.write("#viewSeat table .select:after{content:\"\"; position:absolute; border-top:2px solid white; width:20px; transform : rotate(45deg); transform-origin: 0% 0%; top:5px; left:5px; }\r\n");
      out.write("#viewSeat table .select:before{content:\"\"; position:absolute; border-top:2px solid white; width:20px; transform : rotate(-45deg); transform-origin: 0% 0%; bottom:4px; left:3px; }\r\n");
      out.write("\r\n");
      out.write("#viewSeat table .blank{background:#fff; border:none; padding:0px; margin:-2px;  width:20px; height:21px;  }\r\n");
      out.write("#viewSeat table .blank:hover{cursor:default;}\r\n");
      out.write("#viewSeat table{}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#sviewSeat{margin-top:100px;}\r\n");
      out.write("#sviewSeat table{border-collapse: separate; border-spacing:1px; width:60%}\r\n");
      out.write("\r\n");
      out.write("#sviewSeat table td{padding:2px 1px; overflow:hidden; position:relative;background:#333; color:#fff; text-align:center; min-width:15px; max-width:15px; height:15px;  cursor:pointer; font-size:11px;}\r\n");
      out.write("#sviewSeat table .seats:hover{background:#fff; color:#333}\r\n");
      out.write("#sviewSeat table .select{background:#333; color:#333; background:#ececec;}\r\n");
      out.write("#sviewSeat table .select:after{content:\"\"; position:absolute; border-top:2px solid white; width:20px; transform : rotate(45deg); transform-origin: 0% 0%; top:5px; left:5px; }\r\n");
      out.write("#sviewSeat table .select:before{content:\"\"; position:absolute; border-top:2px solid white; width:20px; transform : rotate(-45deg); transform-origin: 0% 0%; bottom:4px; left:3px; }\r\n");
      out.write("\r\n");
      out.write("#sviewSeat table .blank{background:#fff; border:none; padding:0px; margin:-2px;  width:20px; height:15px;  }\r\n");
      out.write("#sviewSeat table .blank:hover{cursor:default;}\r\n");
      out.write("#sviewSeat table{}\r\n");
      out.write("#sviewSeat table .setInfo{background:#ececec; color:#333; margin-right:10px; cursor:default;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#room{ font-size:25px; padding:10px;}\r\n");
      out.write("#viewSeat .seat .setInfo{background:#ececec; color:#333; margin-right:10px; cursor:default;}\r\n");
      out.write(".view_pot{padding:10px; height:74px; overflow:hidden; vertical-align:top; display: table;}\r\n");
      out.write(".view_pot input{display:inline-block; height:100%; margin:0px; font-size: 15px; width:250px;}\r\n");
      out.write(".view_pot{display:inline-block;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"view_pot\">\r\n");
      out.write("<span>관 이름 </span> <input type=\"text\" id=\"name\"/>   <button class=\"btn_check\">확인</button>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- \r\n");
      out.write("컬럼설정 <input type=\"number\" min=1 max=30 id=\"colset\" />\r\n");
      out.write("행설정 <input type=\"text\" min=1 max=30 id=\"rowset\"/>\r\n");
      out.write("<button id=\"setBlank\">설정</button> -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("$(\"#setBlank\").click(function(){\r\n");
      out.write("\t;\r\n");
      out.write("\tconsole.log($(\"#colset\").val());\t\r\n");
      out.write("\tconsole.log($(\"#rowset\").val());\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"viewList\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"viewSeat\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select name=\"\" id=\"room\"></select>\r\n");
      out.write("<div id=\"sviewSeat\"></div>\r\n");
      out.write("업데이트관 이름 <input type=\"text\" id=\"upname\"/>\r\n");
      out.write("<button class=\"btn_update\">업데이트</button>\r\n");
      out.write("<script>\r\n");
      out.write("var list = null;\r\n");
      out.write("var rowArr = [5, 16];\r\n");
      out.write("\r\n");
      out.write("var colArr = [5, 20];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_seatList(){\r\n");
      out.write("$(\"#room\").empty();\r\n");
      out.write("$.ajax({\r\n");
      out.write("\turl : \"");
      out.print(seat );
      out.write("\",\r\n");
      out.write("\tdataType:\"json\",\r\n");
      out.write("\ttype: \"post\",\r\n");
      out.write("\tdata : { type : \"seatList\"},\r\n");
      out.write("\tsuccess:function(data){\r\n");
      out.write("\t\tconsole.log(data[0].name);\r\n");
      out.write("\t\tlist = data;\r\n");
      out.write("\t\tfor(key in data){\r\n");
      out.write("\t\t\t$(\"#room\").append(\"<option value='\"+key+\"' sid='\"+list[key].sid+\"'>\"+list[key].name+\"</option>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, \terror : function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\tconsole.log(textStatus);\r\n");
      out.write("\t\tconsole.log(errorThrown);\r\n");
      out.write("}, complete : function(){\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("});\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#room\").change(function(){\r\n");
      out.write("\tfn_getSeatList($(this).val());\r\n");
      out.write("\t$(this).attr(\"upval\", new Number($(this).val())+1);\r\n");
      out.write("\tconsole.log(\"셀렉티이드\"+$(this).find(\"option:selected\").text());\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#upname\").val($(this).find(\"option:selected\").text());\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("///////////////////////////////////////////확인용/////////////////////////////////\r\n");
      out.write("function fn_getSeatList(room){\r\n");
      out.write("\tconsole.log(list[room].sid);\r\n");
      out.write("\tshape = list[room].shape;\r\n");
      out.write("\tshape = shape.split(\"|\");\r\n");
      out.write("\tvar sview = $(\"#sviewSeat\");\r\n");
      out.write("\thtml = \"<table class='update_seat'>\";\r\n");
      out.write("\tvar j=0;\r\n");
      out.write("\tvar k=0;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfor(i in shape){\r\n");
      out.write("\t\tif(i==0 && i%27==1){\r\n");
      out.write("\t\t\thtml +=\"<tr>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(i!=0 && i%27==0){\r\n");
      out.write("\r\n");
      out.write("\t\t\thtml+=\"</tr>\";\r\n");
      out.write("\t\t\tj=0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif((shape.length-1) != i){\r\n");
      out.write("\t\t\tif(shape[i].split(\",\")[0]==\"null\"){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\thtml += \"<td class='blank'></td>\"; \r\n");
      out.write("\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif( i%27==0){\r\n");
      out.write("\t\t\t\t\thtml+=\"<td class='setInfo'>\"+abcde[k++]+\"</td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\thtml += \"<td class='seats' seat='\"+shape[i].split(\",\")[0]+\"' variable='\"+shape[i].split(\",\")[1]+\"'>\"+j+\"</td>\"; \r\n");
      out.write("\t\t\t\tj++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write("\tsview.empty();\r\n");
      out.write("\tsview.append(html);\r\n");
      out.write("\tfn_checked();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_checked(){\r\n");
      out.write("\t\t$(\"#sviewSeat table .seats\").each(function(){\r\n");
      out.write("\t\t\tif($(this).attr(\"variable\")!=1){\r\n");
      out.write("\t\t\t\t$(this).toggleClass(\"select\");\r\n");
      out.write("\t\t\t\t$(this).text(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var abcde = [\"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\", \"H\", \"I\", \"J\", \"K\", \"L\", \"N\", \"M\", \"O\", \"P\", \"Q\", \"R\", \"S\", \"T\", \"U\", \"W\", \"X\", \"Y\", \"Z\" ];\r\n");
      out.write("////////////////////////////////인서트용//////////////////////////////\r\n");
      out.write("$(\".btn_check\").click(function(){\r\n");
      out.write("\tvar seatTotal = new Array();\r\n");
      out.write("\r\n");
      out.write("\tvar allSeat = $(\".seat\").find(\"td\");\r\n");
      out.write("\tvar allSeatLength = allSeat.length;\r\n");
      out.write("\tvar seatName = $(\"#name\").val();\r\n");
      out.write("\tconsole.log($(\".seat\").find(\"td\").attr(\"seat\"));\r\n");
      out.write("\tconsole.log(allSeatLength);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i = 0; i < allSeatLength; i++){\r\n");
      out.write("\t\t//if($(\".seat td\")[i].getAttribute(\"class\") != \"blank\"){\r\n");
      out.write("\t\tif($(\".seat td\")[i].getAttribute(\"class\") != \"setInfo\"){\r\n");
      out.write("\t\t\tseatTotal.push($(\".seat td\")[i].getAttribute(\"seat\") + \",\"+ $(\".seat td\")[i].getAttribute(\"variable\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(seat );
      out.write("\",\r\n");
      out.write("\t\tdataType:\"html\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdata : { type : \"seatSeting\" , seatTotal : seatTotal, name : seatName },\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tfn_seatList();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, \terror : function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t}, complete : function(){\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("////////////////////////////////업데이트용//////////////////////////////\r\n");
      out.write("$(\".btn_update\").click(function(){\r\n");
      out.write("\tvar seatTotal = new Array();\r\n");
      out.write("\r\n");
      out.write("\tvar allSeat = $(\".update_seat\").find(\"td\");\r\n");
      out.write("\tvar allSeatLength = allSeat.length;\r\n");
      out.write("\tvar seatName = $(\"#upname\").val();\r\n");
      out.write("\tconsole.log($(\".update_seat\").find(\"td\").attr(\"seat\"));\r\n");
      out.write("\tconsole.log(allSeatLength);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i = 0; i < allSeatLength; i++){\r\n");
      out.write("\t\t//if($(\".seat td\")[i].getAttribute(\"class\") != \"blank\"){\r\n");
      out.write("\t\tif($(\".update_seat td\")[i].getAttribute(\"class\") != \"setInfo\"){\r\n");
      out.write("\t\t\tseatTotal.push($(\".update_seat td\")[i].getAttribute(\"seat\") + \",\"+ $(\".update_seat td\")[i].getAttribute(\"variable\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(seat );
      out.write("\",\r\n");
      out.write("\t\tdataType:\"html\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdata : { type : \"updateSeatSeting\" , seatTotal : seatTotal, name : seatName, sid : $(\"#room\").find(\"option:selected\").attr(\"sid\")},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tfn_seatList();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, \terror : function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t}, complete : function(){\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t});\t \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\".uploadSeat\").click(function(){\r\n");
      out.write("\tconsole.log(seatTotal);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\".seat .seats\").click(function(){\r\n");
      out.write("\t\t$(this).attr(\"variable\", $(this).attr(\"variable\") == 1 ? 0 : 1);\r\n");
      out.write("\t\t$(this).toggleClass(\"select\");\r\n");
      out.write("\t\tvar seatNo= $(this).attr(\"seat\").substring(1,4);\r\n");
      out.write("\t\t//console.log(var seatNo= $(this).attr(\"seat\").substring(1,4));\r\n");
      out.write("\t\t$(this).text($(this).attr(\"variable\") == 0 ? \"\" : seatNo);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#sviewSeat\").on(\"click\",\".seats\", function(){\r\n");
      out.write("\t\tconsole.log(\"test\");\r\n");
      out.write("\t\t$(this).attr(\"variable\", $(this).attr(\"variable\") == 1 ? 0 : 1);\r\n");
      out.write("\t\t$(this).toggleClass(\"select\");\r\n");
      out.write("\t\tvar seatNo= $(this).attr(\"seat\").substring(1,4);\r\n");
      out.write("\t\t//console.log(var seatNo= $(this).attr(\"seat\").substring(1,4));\r\n");
      out.write("\t\t$(this).text($(this).attr(\"variable\") == 0 ? \"\" : seatNo);\r\n");
      out.write("\t});\r\n");
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//칼럼 로우 설정\r\n");
      out.write("$(\"#setBlank\").click(function(){\r\n");
      out.write("\tvar colset = $(\"#colset\").val();\r\n");
      out.write("\tvar rowset = $(\"#rowset\").val();\r\n");
      out.write("\tconsole.log(colset.split(\",\"));\r\n");
      out.write("\tconsole.log(rowset.split(\",\"));\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//좌석을 그리자~\r\n");
      out.write("function fn_initSeat(viewSeat, col, row){\r\n");
      out.write("\tvar col_infor_table = $(\"#col_info\");\r\n");
      out.write("\tvar col_infor_html =\"\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar html =\"<table class='seat'>\";\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i=0; i<row; i++){\r\n");
      out.write("\r\n");
      out.write("\t\tfor(var l=0; l<rowArr.length; l++){\r\n");
      out.write("\t\t\tif(i==rowArr[l]){\r\n");
      out.write("\t\t\t\thtml+= \"<tr>\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tfor(var m =0; m < col+rowArr.length; m++){\r\n");
      out.write("\t\t\t\t\thtml+=\"<td class='blank'></td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcol_infor_html += \"<tr><td class='blank'>\"+abcde[i]+\"</td></tr>\";\r\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\thtml +=\"<tr>\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var j=0; j<col; j++){\r\n");
      out.write("\t\t\tfor(var k=0; k<colArr.length; k++){\r\n");
      out.write("\t\t\t\tif(j==colArr[k]){\r\n");
      out.write("\t\t\t\t\thtml+= \"<td class='blank'></td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(j==0){\r\n");
      out.write("\t\t\t\thtml+=\"<td class='setInfo'>\"+abcde[i]+\" </td>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\thtml+= \"<td class='seats' seat='\"+(abcde[i]+j)+\"' variable='\"+1+\"'>\"+j+\"</td>\";\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\thtml +=\"</tr>\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t \t//col_infor_html += \"<tr><td>\"+abcde[i]+\"</td></tr>\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tviewSeat.append(html);\r\n");
      out.write("\tcol_infor_table.append(col_infor_html);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var viewSeat = $(\"#viewSeat\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("fn_initSeat(viewSeat, 25, 19);\r\n");
      out.write("\r\n");
      out.write("function fn_delete(localCode, name){\r\n");
      out.write("\tconsole.log(name);\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(localPath );
      out.write("\",\r\n");
      out.write("\t\tdataType:\"html\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdata : { type : \"delete\", localCode : localCode},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t \tconsole.log(data);\r\n");
      out.write("\t\tfn_showList();\r\n");
      out.write("\t\t}, \terror : function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t}, complete : function(){\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t});\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("fn_seatList() \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
