/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-20 04:39:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.cinema.admin.model.vo.Local;
import com.cinema.user.model.vo.*;
import com.cinema.admin.model.vo.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header_non_wrap.jsp", Long.valueOf(1526787995261L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.cinema.user.model.vo");
    _jspx_imports_packages.add("com.cinema.admin.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.cinema.admin.model.vo.Local");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	int cPage;
		try {
			cPage = Integer.parseInt(request.getParameter("cPage"));
		} catch (NumberFormatException e) {
			//cPage 파라미터가 값이 없거나, 부정 입력된 경우 대비 
			cPage=1;
		}
    
      out.write("  \r\n");
      out.write("<div style=\"background:#0E1B45;\"><div class=\"wrap\"><img src=\"/cinema/data/bean.jpg\"  width=100%/></div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	User userSession = null;
	String userId = "";
	if(session.getAttribute("userSession") != null){
		userSession = (User)session.getAttribute("userSession");
	}else{
		
	}

	String path = request.getContextPath();

	
	String MovieListPath = path+"/movie/showMovieList";
	String JoinUser = path+"/user/join";
	String BoardPath = path + "/board/boardView";
	String RecomandMoviePath = path+"/movie/recommand.do";
	String TheatersPath = path+"/userTheater";
	
	String Managerlogin ="/managerLogin";
	
	
	//관리자가 아닌경우 
	Manager sessionManager = (Manager)request.getSession(true).getAttribute("managerSession");
	
	
	String view="";
	if(sessionManager != null) {
		Managerlogin = path + "/manager/movie";
	}else{
		Managerlogin = path + "/managerLogin";
	}

	Cookie[] cookies = request.getCookies();
	
	boolean usaveId = false;
	String userIdSaved = "";
	
   	if(cookies !=null){
   		System.out.println("--------------------------------");
   		System.out.println("브라우져가 전송한 쿠키목록");
   		System.out.println("--------------------------------");
		for(Cookie c : cookies ){
			String key = c.getName();
			String value = c.getValue();
	   		System.out.println("쿠키가요 ===> " + key + " : " + value );
	   		
	   		//아이디저장 쿠키검사
	   		if("usaveId".equals(key)){
	   			usaveId = true;
	   			userIdSaved = value;
	   		}else{
	   			
	   		}
		}   		
   		System.out.println("--------------------------------");
   	}
   	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(path );
      out.write("/js/date.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/css/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_login_pop(){\r\n");
      out.write("\t$(\".login_pop\").toggle();\r\n");
      out.write("\tconsole.log($(\".login_pop\"));\r\n");
      out.write("}\r\n");
      out.write("function fn_login(){\r\n");
      out.write("\t$id = $(\"#id\").val();\r\n");
      out.write("\t$pw = $(\"#pw\").val();\r\n");
      out.write("\t$usaveId = $(\"#usaveId\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(path );
      out.write("/login/userlogin\", \r\n");
      out.write("\t\tdata : {id : $id, pw : $pw, usaveId : $usaveId},\r\n");
      out.write("\t\ttype : \"post\", \r\n");
      out.write("\t\tdataType : \"html\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tlocation.href=\"/cinema\";\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror :function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(){\r\n");
      out.write("\t\t\tconsole.log(\"ajax 어찌됬던 종료!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_login_hidden(){\r\n");
      out.write("\t$id = $(\".loginBox .login_hidden_id\").val();\r\n");
      out.write("\t$pw = $(\".loginBox .login_hidden_pw\").val();\r\n");
      out.write("\t$usaveId = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(path );
      out.write("/login/userlogin\", \r\n");
      out.write("\t\tdata : {id : $id, pw : $pw, usaveId : $usaveId},\r\n");
      out.write("\t\ttype : \"post\", \r\n");
      out.write("\t\tdataType : \"html\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tlocation.href=\"/cinema\";\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror :function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!!\");\r\n");
      out.write("\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(){\r\n");
      out.write("\t\t\tconsole.log(\"ajax 어찌됬던 종료!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function fn_join(){\r\n");
      out.write("\tlocation.href=\"");
      out.print(JoinUser);
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_manager_login(){\r\n");
      out.write("\tlocation.href=\"");
      out.print(Managerlogin);
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("header{ border-bottom:3px solid #1986ff; position:relative; }\r\n");
      out.write("header h1{float:left;}\r\n");
      out.write("header h1 a{padding:10px; display:inline-block;}\r\n");
      out.write("nav{overflow:hidden;}\r\n");
      out.write("nav::after{content:\"\"; clear:both;}\r\n");
      out.write("nav > ul {float:left; margin-left:50px; overflow:hidden;}\r\n");
      out.write("nav > ul > li{float:left; border-left:1px solid #ececec; border-right:1px solid #ececec; min-width:100px; text-align:center;}\r\n");
      out.write("nav > ul > li a{padding:20px; display:inline-block; width:100%;}\r\n");
      out.write("nav > ul > li a:hover{  color:#1986ff; font-weight:bold;}\r\n");
      out.write(".login_pop{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:280px;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\tbackground:#fff;\r\n");
      out.write("\tright:30px;\r\n");
      out.write("\ttop:61px;\r\n");
      out.write("\tborder-top:2px solid #1986ff;\r\n");
      out.write("\tborder-radius:0px 0px 3px 3px;\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("}\r\n");
      out.write(".login_pop input{\r\n");
      out.write("\tmargin-bottom:10px;\r\n");
      out.write("\tborder-radius:2px;\r\n");
      out.write("\tborder-style:none;\r\n");
      out.write("\tborder:1px solid #ececec;\r\n");
      out.write("\toutline:none;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write(".login_section{\r\n");
      out.write("\tpadding:20px;\r\n");
      out.write("\toverflow:hidden; \r\n");
      out.write("\tposition:relative;\r\n");
      out.write("}\r\n");
      out.write(".login_section h3{\r\n");
      out.write("display:block;\r\n");
      out.write("padding:15px 0px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".login_pop input:focus{\r\n");
      out.write("border:1px solid #1986ff}\r\n");
      out.write("#id{-webkit-appearance :none; width:100%;}\r\n");
      out.write("#pw{-webkit-appearance :none; width:100%;}\r\n");
      out.write(".login_adversting {position:absolute; bottom:0px; height:60px;}\r\n");
      out.write(".login_adversting img{ width:100%;}\r\n");
      out.write(".input_section{float:left; width:60%;}\r\n");
      out.write(".login_btn_section{margin-left:10px; float:right; width:35%; }\r\n");
      out.write(".btn_login{height:86px; width:100%;}\r\n");
      out.write(".login_saveId{clear:both; font-size:12px; padding-top:10px; }\r\n");
      out.write(".login_saveId span{cursor:pointer;}\r\n");
      out.write("#saveId{vertical-align: top; }\r\n");
      out.write(".user_logged{padding:0px 10px; font-size:12px; height:60px; border-right:none;}\r\n");
      out.write(".user_logged span{display:inline-block; padding:21px 0px; }\r\n");
      out.write(".logout_btn{cursor:pointer;}\r\n");
      out.write(".logo{float:left;}\r\n");
      out.write(".logo a{padding:0px; padding-top:18px; display:inline-block; letter-spacing: 2px;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<h3 class=\"logo\"><a href=\"");
      out.print( path);
      out.write("\"> MVCINEMA </a></h3>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print( MovieListPath );
      out.write("\">영화</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print( RecomandMoviePath);
      out.write("\">추천영화</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print( TheatersPath );
      out.write("\">영화관</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(BoardPath );
      out.write("\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t");
 if(userSession == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:fn_login_pop()\" >로그인</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:fn_manager_login()\">관리자</a></li>\t\t\t\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"user_logged\">\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print( userSession.getName() );
      out.write("님, 안녕하세요.</span> &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<span class=\"my_infor\" onclick=\"fn_showInfo()\" style=\"cursor:pointer;\">내정보보기</span> &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<span class=\"logout_btn\" onclick=\"fn_logout()\">로그아웃</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"login_pop\">\r\n");
      out.write("\t\t<div class=\"login_section\">\r\n");
      out.write("\t\t");
 if(userSession == null) {
      out.write("\r\n");
      out.write("\t\t\t<h3>MVCINEMA 로그인</h3>\r\n");
      out.write("\t\t\t<div class=\"input_section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"id\" id=\"id\" placeholder=\"아이디\" value =\"");
      out.print( usaveId ? userIdSaved : "" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"pw\" id=\"pw\" placeholder=\"비밀번호\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"login_btn_section\">\r\n");
      out.write("\t\t\t\t<button onclick=\"fn_login()\" class=\"btn_login\">로그인</button>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"login_saveId\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"usaveId\" id=\"usaveId\" ");
      out.print( usaveId ? "checked":"" );
      out.write(" />\r\n");
      out.write("\t\t\t\t<label for=\"usaveId\">아이디 저장</label>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp; <span onclick=\"fn_join()\">회원가입</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( userSession.getName() );
      out.write(" 님, 안녕하세요.\r\n");
      out.write("\t\t\t<button onclick=\"fn_login()\">내정보보기</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"login_adversting\">\r\n");
      out.write("\t\t\t<img src=\"/cinema/data/adversting.jpg\" alt=\"\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("function fn_logout(){\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href=\"/cinema/user/logout\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function fn_showInfo(){\r\n");
      out.write("\tlocation.href=\"/cinema/users?type=viewInfo\";\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("\t<section id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.title_wrap{background:black; }\r\n");
      out.write("\t.title_wrap div{height:300px; width:100%; overflow:hidden; background : url(\"/cinema/data/special.jpg\") no-repeat no-repeat center center}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"title_wrap\">\r\n");
      out.write("\t<div></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\tth, td, tr{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.tab{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\ttop : 0;\r\n");
      out.write("\t\tleft : 0;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.div-enroll{\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t\tposition: fixed;\r\n");
      out.write("\t\ttop : 10%;\r\n");
      out.write("\t\tleft : 40%;\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable#notice-table{\r\n");
      out.write("\t\tdisplay : block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.update-event{\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.jwrap img{\r\n");
      out.write("\t\twidth: 250px;\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.div-inline{\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap jwrap\">\r\n");
      out.write("\t<div class='tab' id='noticeList'>공지사항</div>\r\n");
      out.write("\t<div class='tab' id='eventList'>이벤트</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 공지사항 -->\r\n");
      out.write("\t<div id=\"boardView\"></div>\r\n");
      out.write("\t<div id=\"none\"></div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//페이지 로드시, noticeList 버튼 클릭\r\n");
      out.write("\t\twindow.onload = pageLoad;\r\n");
      out.write("\t    function pageLoad(){\r\n");
      out.write("\t    \tdocument.getElementById(\"noticeList\").click();\r\n");
      out.write("\t    };\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t//공지사항 탭\r\n");
      out.write("\t\t\t$(\"#noticeList\").click(function(){\r\n");
      out.write("\t\t\t\tvar noticeType = this.id;\r\n");
      out.write("\t\t\t\t//$(\"div#none\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\t\tdata : {listType : noticeType, cPage : ");
      out.print(cPage);
      out.write("},\r\n");
      out.write("\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar nhtml = \"\";\r\n");
      out.write("\t\t\t\t\t\tvar html = \"<table id='notice-table'>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<tr><th>no</th><th>지역/영화관</th><th>제목</th><th>등록일</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\t\treturn b.bdid-a.bdid;\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tvar pageBar=\"\";\r\n");
      out.write("\t\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\t\tvar d = new Date(i.regdate.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<tr>\"+ \"<td>\" + i.bdid + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td>\" + i.tinfo + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td> <a href='");
      out.print(request.getContextPath());
      out.write("/board/boardDetail?bdid=\"+i.bdid+\"'>\" + (i.title==null?\"제목없음\":i.title) + \"</a></td>\";\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<td>\" + d.getFullYear() + \"-\" + (d.getMonth()+1) + \"-\" + d.getDate() + \"</td>\" +\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tpageBar = i.pageBar;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\thtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tconsole.log(pageBar);\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div id='pageBar'>\"+pageBar+\"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#boardView\").html(nhtml);\r\n");
      out.write("\t\t\t\t\t\t$(\"div#none\").html(html);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"div#none\").on(\"click\",\"#\"+");
      out.print(cPage);
      out.write(", function(){\r\n");
      out.write("\t\t\t\t\t\t\tpageBar = \"<span value='\"+");
      out.print(cPage-1);
      out.write("+\"'>\"+");
      out.print(cPage-1);
      out.write("+\"</span><a href=/project/board/boardView?cPage=\"+");
      out.print(cPage);
      out.write("+\" id='\"+");
      out.print(cPage);
      out.write("+\"'><span value='\"+");
      out.print(cPage);
      out.write("+\"'>\"+");
      out.print(cPage);
      out.write("+\"</span></a>\";\r\n");
      out.write("\t\t\t\t\t\t\tvar h=\"<div id='pageBar'>\"+pageBar+\"</div>\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"div#none\").append(h);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});//ajax\r\n");
      out.write("\t\t\t});//notice 버튼\r\n");
      out.write("\t\t});//function\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 이벤트 팝업창 -->\r\n");
      out.write("\t<div id=\"event-popup\" class='div-enroll'>\r\n");
      out.write("\t\t<span class=\"close\">&times;</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar pPage=6;\r\n");
      out.write("\t\tvar lPage=6;\r\n");
      out.write("\t\t$(\"#eventList\").click(function(){\r\n");
      out.write("\t\t\tfn_showEventTab();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_showEventTab(){\r\n");
      out.write("\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\thtml += \"<input type='radio' name='event-status' id='present' class='present' checked><label for='present'>진행 중인 이벤트</label>\";\r\n");
      out.write("\t\t\thtml += \"<input type='radio' name='event-status' id='last' class='last'><label for='last'>지난 이벤트</label>\";\t\t\t\r\n");
      out.write("\t\t\t$(\"#boardView\").html(html);\r\n");
      out.write("\t\t\tfn_add_present();\r\n");
      out.write("\t\t\t$(\"#boardView\").on(\"change\",\"[name=event-status]\",function(){\r\n");
      out.write("\t\t\t\tif(this.id==\"present\"){\r\n");
      out.write("\t\t\t\t\tfn_add_present();\t\r\n");
      out.write("\t\t\t\t\tlPage=6;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(this.id==\"last\"){\r\n");
      out.write("\t\t\t\t\tfn_add_last();\t\r\n");
      out.write("\t\t\t\t\tpPage=6;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fn_add_present(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\tdata : {listType : \"eventList\", status: \"present\", pPage: pPage},\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar phtml=\"\";\r\n");
      out.write("\t\t\t\t\tvar presentEventCnt=0;\r\n");
      out.write("\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\treturn a.order-b.order;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\tvar d = new Date();\r\n");
      out.write("\t\t\t\t\t\tvar ds = new Date(i.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\tvar de = new Date(i.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t//끝나는 시간이 현재 시간보다 크거나 같으면 현재 진행중인 이벤트\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<div class='div-inline' id='eventp\"+presentEventCnt+\"'>\"\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<table class='table' id=\"+i.bdid+\">\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td>\"+ \"<img id='clickEvent' src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ i.img +\"' / >\" + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td> \"+ i.title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"<tr><td>\" + ds.getFullYear() + \"-\" + (ds.getMonth()+1) + \"-\" + ds.getDate() + \" ~ \"  + de.getFullYear() + \"-\" + (de.getMonth()+1) + \"-\" + de.getDate()+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tphtml += \"</div>\"\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt%3==2){\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt==(pPage-1)){\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"<input type='button' id='add-present' value='더보기'>\";\t\t\r\n");
      out.write("\t\t\t\t\t\t\tphtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tpresentEventCnt++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").html(phtml);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//지난 이벤트의 더보기 버튼\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"#add-present\",function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\tif(presentEventCnt==pPage){\r\n");
      out.write("\t\t\t\t\t\t\tpPage += 6;\r\n");
      out.write("\t\t\t\t\t\t\tfn_add_present();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//on 동적으로 부모의 자식이벤트를 달아준다. //단, 부모는 동적으로 생성되면 안된다.\r\n");
      out.write("\t\t\t\t\t//현재 진행중인 이벤트, 지난 이벤트의  수정 팝업창\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"table.table\", function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(this.id);\r\n");
      out.write("\t\t\t\t\t\tvar html=\"\";\r\n");
      out.write("\t\t\t\t\t\tfor(var a in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar b = data[a];\r\n");
      out.write("\t\t\t\t\t\t\tif(b.bdid==this.id){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(b.bdid);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ds = new Date(b.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar de = new Date(b.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsYear = ds.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsMonth = ds.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsDate = ds.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deYear = de.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deMonth = de.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deDate = de.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsMonth = \"0\"+dsMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsDate = \"0\"+dsDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeMonth = \"0\"+deMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeDate = \"0\"+deDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='bdid' value='\"+b.bdid+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='old_file' value='\"+b.img+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<span class='close'>&times;</span><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<h3>\"+b.title+\"</h3>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p>\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \" ~ \"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"</p><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<hr><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ b.img +\"'/>\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").html(html);\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").on(\"click\",\".close\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction fn_add_last(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/board/boardAjax1.do\",\r\n");
      out.write("\t\t\t\tdata : {listType : \"eventList\", status: \"last\", lPage: lPage},\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar endEventCnt=0;\r\n");
      out.write("\t\t\t\t\tvar lhtml=\"\";\r\n");
      out.write("\t\t\t\t\tdata.sort(function(a,b){\r\n");
      out.write("\t\t\t\t\t\treturn a.order-b.order;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tfor(var index in data){\r\n");
      out.write("\t\t\t\t\t\tvar i = data[index];\r\n");
      out.write("\t\t\t\t\t\tvar ds = new Date(i.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\tvar de = new Date(i.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<div class='div-inline' id='eventl\"+endEventCnt+\"'>\"\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<table class='table' id=\"+i.bdid+\">\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\"+ \"<img id='clickEvent' src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ i.img +\"'/ >\" + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\" + i.title + \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"<tr><td>\" + ds.getFullYear() + \"-\" + (ds.getMonth()+1) + \"-\" + ds.getDate() + \" ~ \"  + de.getFullYear() + \"-\" + (de.getMonth()+1) + \"-\" + de.getDate() +\"</td>\"+\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\t\tlhtml += \"</div>\"\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt%3==2){\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt==(lPage-1)){\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(endEventCnt+\"???\");\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"<input type='button' id='add-last' value='더보기'>\";\t\t\r\n");
      out.write("\t\t\t\t\t\t\tlhtml += \"</br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tendEventCnt++;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").html(lhtml);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//지난 이벤트의 더보기 버튼\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"#add-last\",function(){\r\n");
      out.write("\t\t\t\t\t\t$(this).css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\tif(endEventCnt==lPage){\r\n");
      out.write("\t\t\t\t\t\t\tlPage += 6;\r\n");
      out.write("\t\t\t\t\t\t\tfn_add_last();\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//on 동적으로 부모의 자식이벤트를 달아준다. //단, 부모는 동적으로 생성되면 안된다.\r\n");
      out.write("\t\t\t\t\t//현재 진행중인 이벤트, 지난 이벤트의  수정 팝업창\r\n");
      out.write("\t\t\t\t\t$(\"div#none\").on(\"click\",\"table.table\", function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(this.id);\r\n");
      out.write("\t\t\t\t\t\tvar html=\"\";\r\n");
      out.write("\t\t\t\t\t\tfor(var a in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar b = data[a];\r\n");
      out.write("\t\t\t\t\t\t\tif(b.bdid==this.id){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(b.bdid);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar ds = new Date(b.startterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar de = new Date(b.endterm.replace(/ /gi, \"\").replace(/[^0-9]/g,\"-\"));\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsYear = ds.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsMonth = ds.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar dsDate = ds.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deYear = de.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deMonth = de.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar deDate = de.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsMonth = \"0\"+dsMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(dsDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdsDate = \"0\"+dsDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deMonth<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeMonth = \"0\"+deMonth;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tif(deDate<10){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdeDate = \"0\"+deDate\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='type' value='updateEvent'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='bdid' value='\"+b.bdid+\"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<input type='hidden' name='old_file' value='\"+b.img+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<span class='close'>&times;</span><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<h3 class='event-popup'>\"+b.title+\"</h3>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<p class='event-popup'>\"+dsYear + \"-\" + dsMonth + \"-\" + dsDate + \" ~ \"  + deYear + \"-\" + deMonth + \"-\" + deDate+\"</p><br/>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<hr class='event-popup'><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\thtml += \"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+ b.img +\"'/ class='event-popup'>\";\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").html(html);\r\n");
      out.write("\t\t\t\t\t\t$(\"#event-popup\").on(\"click\",\".close\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#event-popup\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("<style>\r\n");
      out.write("#notice-table{width:100%;}\r\n");
      out.write("\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
